
// list of valid character sets based on https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html
export enum CharsetType {
    ascii,
    big5,
    binary,
    cp1250,
    cp1251,
    cp1256,
    cp1257,
    cp850,
    cp852,
    cp866,
    cp932,
    dec8,
    eucjpms,
    euckr,
    gb18030,
    gb2312,
    gbk,
    geostd8,
    greek,
    hebrew,
    hp8,
    keybcs2,
    koi8r,
    koi8u,
    latin1,
    latin2,
    latin5,
    latin7,
    macce,
    macroman,
    sjis,
    swe7,
    tis620,
    ucs2,
    ujis,
    utf16,
    utf16le,
    utf32,
    utf8,
    utf8mb4
}

export const charsetList : { [key: number]: string } = {
    [CharsetType.ascii]: "ascii",
    [CharsetType.big5]: "big5",
    [CharsetType.binary]: "binary",
    [CharsetType.cp1250]: "cp1250",
    [CharsetType.cp1251]: "cp1251",
    [CharsetType.cp1256]: "cp1256",
    [CharsetType.cp1257]: "cp1257",
    [CharsetType.cp850]: "cp850",
    [CharsetType.cp852]: "cp852",
    [CharsetType.cp866]: "cp866",
    [CharsetType.cp932]: "cp932",
    [CharsetType.dec8]: "dec8",
    [CharsetType.eucjpms]: "eucjpms",
    [CharsetType.euckr]: "euckr",
    [CharsetType.gb18030]: "gb18030",
    [CharsetType.gb2312]: "gb2312",
    [CharsetType.gbk]: "gbk",
    [CharsetType.geostd8]: "geostd8",
    [CharsetType.greek]: "greek",
    [CharsetType.hebrew]: "hebrew",
    [CharsetType.hp8]: "hp8",
    [CharsetType.keybcs2]: "keybcs2",
    [CharsetType.koi8r]: "koi8r",
    [CharsetType.koi8u]: "koi8u",
    [CharsetType.latin1]: "latin1",
    [CharsetType.latin2]: "latin2",
    [CharsetType.latin5]: "latin5",
    [CharsetType.latin7]: "latin7",
    [CharsetType.macce]: "macce",
    [CharsetType.macroman]: "macroman",
    [CharsetType.sjis]: "sjis",
    [CharsetType.swe7]: "swe7",
    [CharsetType.tis620]: "tis620",
    [CharsetType.ucs2]: "ucs2",
    [CharsetType.ujis]: "ujis",
    [CharsetType.utf16]: "utf16",
    [CharsetType.utf16le]: "utf16le",
    [CharsetType.utf32]: "utf32",
    [CharsetType.utf8]: "utf8",
    [CharsetType.utf8mb4]: "utf8mb4"
};